const toolbar = {
  bold: true,
  italic: true,
  header: true,
  underline: true,
  strikethrough: true,
  mark: true,
  superscript: true,
  subscript: true,
  quote: true,
  ol: true,
  ul: true,
  link: true,
  imagelink: true,
  code: true,
  table: true,
  fullscreen: true,
  readmodel: true,
  htmlcode: false,
  help: false,
  undo: false,
  redo: false,
  trash: false,
  save: false,
  navigation: false,
  alignleft: true,
  aligncenter: true,
  alignright: true,
  subfield: false,
  preview: true,
}

export default toolbar
